name: Sonar Continuos Integration
env:
  DOTNET_VERSION: '8.0.204'                     # la versión de .NET
  SONAR_ORG: 'sergio-colque-ponce'                    # Nombre de la organización de sonar cloud
  SONAR_PROJECT: 'sergio-colque-ponce_apibank'        # Key ID del proyecto de sonar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analisys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restaurar los paquetes
        run: cd Bank && dotnet restore
      - name: Ejecutar pruebas
        run: cd Bank && dotnet test --collect:"XPlat Code Coverage;Format=opencover"
      - name: Instalar Scanner
        run: dotnet tool install -g dotnet-sonarscanner
      - name: Ejecutar escaneo
        run: | 
          cd Bank
          dotnet sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="*/*/*/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Pack NuGet package
        run: cd Bank && dotnet pack Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --output .
      - name: Publish package to GitHub Packages
        run: cd Bank && dotnet nuget push *.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.SONAR_TOKEN }} --skip-duplicate
      - name: Verificar existencia de cobertura.png
        run: cd Bank && ls -l cobertura.png || echo "Archivo cobertura.png no encontrado"
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        id: release_notes
        run: |
          echo "## Changelog" > RELEASE_NOTES.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: "RELEASE_NOTES.md"
          token: ${{ secrets.SONAR_TOKEN }}