name: Sonar Continuos Integration
env:
  DOTNET_VERSION: '8.0'                     # la versión de .NET
  SONAR_ORG: 'sergio-colque-ponce'                    # Nombre de la organización de sonar cloud
  SONAR_PROJECT: 'sergio-colque-ponce_lab-2025-i-cps-u1-01-csharp-sergio-colque-ponce'        # Key ID del proyecto de sonar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analisys
    runs-on: ubuntu-latest
    steps:
      - name: Env GH_TOKEN
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN_V2 }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Instalar Scanner
        run: dotnet tool install -g dotnet-sonarscanner
      - name: Restaurar dependencias
        run: dotnet restore "Bank/Bank.sln"
      - name: Ejecutar pruebas
        run: dotnet test "Bank/Bank.sln" --collect:"XPlat Code Coverage;Format=opencover"
      - name: Iniciar análisis SonarQube
        run: dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="Bank/**/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
      - name: Compilar solución
        run: dotnet build "Bank/Bank.sln"
      - name: Finalizar análisis SonarQube
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Crear paquete NuGet
        run: dotnet pack "Bank/Bank.sln" --configuration Release --output ./packages
      - name: Publicar en GitHub Packages
        #run: dotnet nuget push ./packages/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_TOKEN }} --skip-duplicate
        run: dotnet nuget push ./packages/*.nupkg --source "https://nuget.pkg.github.com/Sergio-Colque-Ponce/index.json" --api-key ${{ secrets.GH_TOKEN_V2 }} --skip-duplicate
  release:
    name: Generar RELEASE
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generar tag
        id: generate_tag
        run: echo "NAME=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Obtener comentarios commits
        id: changelog
        run: |
          echo "## Cambios en la versión ${{ env.NAME }}" > release.md
          git log --pretty=format:"- %s" -n 10 >> release.md
      - name: Crear TAG
        run: |
          git tag ${{ env.NAME }}
          git push origin ${{ env.NAME }}
      - name: Crear RELEASE
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.NAME }}
          name: "Release ${{ env.NAME }}"
          bodyFile: "release.md"
          token: ${{ secrets.GH_TOKEN_V2 }}
          replacesArtifacts: true
