name: Sonar Continuos Integration
env:
  DOTNET_VERSION: '8.0'                     # la versión de .NET
  SONAR_ORG: 'sergio-colque-ponce'                    # Nombre de la organización de sonar cloud
  SONAR_PROJECT: 'sergio-colque-ponce_lab-2025-i-cps-u1-01-csharp-sergio-colque-ponce'        # Key ID del proyecto de sonar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analisys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Instalar Scanner
        run: dotnet tool install -g dotnet-sonarscanner
      - name: Restaurar dependencias
        run: dotnet restore "Bank/Bank.sln"
      - name: Ejecutar pruebas
        run: dotnet test "Bank/Bank.sln" --collect:"XPlat Code Coverage;Format=opencover"
      - name: Iniciar análisis SonarQube
        run: dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="Bank/**/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
      - name: Compilar solución
        run: dotnet build "Bank/Bank.sln"
      - name: Finalizar análisis SonarQube
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
