name: Sonar Continuos Integration
env:
  DOTNET_VERSION: '8.0'                     # la versión de .NET
  SONAR_ORG: 'sergio-colque-ponce'                    # Nombre de la organización de sonar cloud
  SONAR_PROJECT: 'sergio-colque-ponce_lab-2025-i-cps-u1-01-csharp-sergio-colque-ponce'        # Key ID del proyecto de sonar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analisys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Instalar Scanner
        run: dotnet tool install -g dotnet-sonarscanner
      - name: Restaurar dependencias
        run: dotnet restore "Bank/Bank.sln"
      - name: Ejecutar pruebas
        run: dotnet test "Bank/Bank.sln" --collect:"XPlat Code Coverage;Format=opencover"
      - name: Iniciar análisis SonarQube
        run: dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="Bank/**/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
      - name: Compilar solución
        run: dotnet build "Bank/Bank.sln"
      - name: Finalizar análisis SonarQube
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Crear paquete NuGet
        run: dotnet pack "Bank/Bank.sln" --configuration Release --output ./packages
      - name: Publicar en GitHub Packages
        run: dotnet nuget push ./packages/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GH_TOKEN }} --skip-duplicate
        #run: dotnet nuget push ./packages/*.nupkg --source "https://nuget.pkg.github.com/Sergio-Colque-Ponce/index.json" --api-key ${{ secrets.GH_TOKEN }} --skip-duplicate
  release:
    name: Crear GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generar RELEASE
        id: release_notes
        run: |
          echo "## Changelog" > RELEASE_NOTES.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s" >> RELEASE_NOTES.md

      - name: Crear GitHub RELEASE
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: "RELEASE_NOTES.md"
          token: ${{ secrets.SONAR_TOKEN }}
